version: '3.8'

services:
  notion-mcp-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      NOTION_TOKEN: your_notion_integration_token_here
      NOTION_DATABASE_ID: your_database_id_here
      PORT: 3000
    restart: unless-stopped
